export { default as Layout } from './Layout/Layout.tsx'
export { default as Home } from './Home/Home.tsx'
export { default as Service } from './Service/Service.tsx'
export { default as Contact } from './Contact/Contact.tsx'
export { default as Connexion } from './Connexion/Connexion.tsx'
